"""Initial database tables

Revision ID: 27369d0881b5
Revises: 
Create Date: 2022-07-06 01:10:53.426438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27369d0881b5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create schema youtube")
    op.create_table(
        "collection_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "pull_datetime",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("complete", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="youtube",
    )
    op.create_table(
        "conversion_rule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parsed_title", sa.String(), nullable=False),
        sa.Column("final_title", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="youtube",
    )
    op.create_table(
        "video",
        sa.Column("unique_youtube_id", sa.String(), nullable=False),
        sa.Column("publish_date", sa.DateTime(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("game", sa.String(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("unique_youtube_id"),
        schema="youtube",
    )
    op.create_table(
        "processed_stat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column("collection_event_id", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Integer(), nullable=False),
        sa.Column("ratio_likes_views", sa.Float(), nullable=False),
        sa.Column("ratio_comments_views", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_event_id"],
            ["youtube.collection_event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["youtube.video.unique_youtube_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="youtube",
    )
    op.create_table(
        "raw_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column("collection_event_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("etag", sa.String(), nullable=False),
        sa.Column("snippet", sa.String(), nullable=False),
        sa.Column("content_details", sa.String(), nullable=False),
        sa.Column("statistics", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_event_id"],
            ["youtube.collection_event.id"],
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["youtube.video.unique_youtube_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="youtube",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("raw_data", schema="youtube")
    op.drop_table("processed_stat", schema="youtube")
    op.drop_table("video", schema="youtube")
    op.drop_table("conversion_rule", schema="youtube")
    op.drop_table("collection_event", schema="youtube")
    op.execute("drop schema youtube")
    # ### end Alembic commands ###
